# Generated by Django 4.1.2 on 2022-10-13 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_block_collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wagtailblockcollectionsettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
