kind: pipeline
name: django backend
type: docker

steps:
- name: install requirements
  image: python
  commands:
    - pip install -r requirements.txt
- name: pypi_publish
  image: plugins/pypi
  settings:
    username:
      from_secret: pypi_username
    password:
      from_secret: pypi_password
  when:
    event:
      - tag

---
kind: pipeline
name: docs
type: docker

steps:
- name: build the docs
  image: python:latest
  commands:
  - pip install -r docs/requirements.txt
  - mkdocs build
- name: build docker image
  image: plugins/docker
  settings:
    username:
      from_secret: username
    password:
      from_secret: password
    repo: registry.sliceofbits.com/wagtail-block-collection-docs
    registry: registry.sliceofbits.com/
    tags: latest
  when:
    branch:
    - master
    event:
    - push